### ISSUE TITLE
More Logos

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/ubq.fi#34]
We need more logos on our site for social credibility. 
We should have logos of all 12 EVMs we support payouts on
Uniswap to mention its permit2
Partners like MakerDAO
and more. TBC

---

Need to find all vector images or create them and make pure they are pure white as we did with the investor logos.

**Comment by zugdev** [comment]
What are those 12 EVMs?

**Comment by 0x4007** [comment]
Where permit2 is deployed basically. So i know for sure there's at least ethereum, gnosis chain, optimism. Its supposed to be deployed at the same address everywhere maybe you can check the docs or manually at the same address

**Comment by zugdev** [comment]
Got 10 out of 12 chains from https://docs.uniswap.org/contracts/v3/reference/deployments/ and also Gnosis which wasn't on the list.

I have:

- Ethereum

- Arbitrum

- Optimism

- BNB

- Avalanche

- Celo

- ZkSync

- Polygon

- Base

- Blast

- Gnosis

The ones I didn't get are Zora and WorldChain. How should I proceed?

**Comment by 0x4007** [comment]
Ideally we should vectorize any large logo we can find and make use

**Comment by zugdev** [comment]
Ok I have them all. Should I add them to the repo?

**Comment by 0x4007** [comment]
You can try dropping them into the index in a pull

**Comment by zugdev** [comment]
Should I create a section for it? Or do you just want the code and you'll arrange it?

**Comment by 0x4007** [comment]
Make a draft and I'll go from there

**Comment by 0x4007** [comment]
@ubiquityos tell me what you know about the logos
