### ISSUE TITLE
UBQ.Fi: Fix top menu on front end

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/ubq.fi#6]
Top menu does not generate nor propagate properly on all front end pages in desktop mode.  Does not load at all on mobile version. Need to fix so works on both.

---

### Updated Specification

- ubq.fi page only.
- We have a top menu visible only on desktop that needs to be visible on mobile in the form of a hamburger menu.
- HTML + CSS only (use a checkbox to toggle state using pure CSS exactly like we did on the uad.ubq.fi UI)
- Code can be copied from uad.ubq.fi for checkbox state logic.

**Comment by pavlovcik** [comment]
When you say "all" pages that's referring to dao.ubq.fi which unfortunately is a separate codebase and makes it a much larger project. This should be to redesign the top menu for mobile on the ubq.fi index only.

**Comment by devpanther** [comment]
So, is he referring to dao.ubq.fi or ubq.fi home page

**Comment by devpanther** [comment]
Alright, i'd get on it..

I see its just a centered logo for now, will create a PR with fix soon

**Comment by pavlovcik** [comment]
Be sure to click on the centered logo. It will reveal the top navigation bar on desktop. It is hidden with a media query on mobile.

**Comment by devpanther** [comment]
> Be sure to click on the centered logo. It will reveal the top navigation bar on desktop. The top navigation bar is hidden with a media query on mobile.

Can i have access for a new branch and PR or i'd need to work on a fork?

**Comment by pavlovcik** [comment]
Fork. 

https://dao.ubq.fi/devpool-flow

**Comment by devpanther** [comment]
> Fork.
> 
> https://dao.ubq.fi/devpool-flow

Okay, moved the codes to my fork.. created a PR and made it a draft, can you link to this issue and check?

**Comment by devpanther** [comment]
@pavlovcik Feel free to test and provide feedback

**Comment by devpanther** [comment]
> @devpanther would you please post your wallet address here?

0xf76F1ACB66020f893c95371f740549F312DEA3f1

**Comment by pavlovcik** [comment]
https://etherscan.io/address/0xefC0e701A824943b469a694aC564Aa1efF7Ab7dd

**Comment by pavlovcik** [comment]
Had to revert 

https://github.com/ubiquity/ubq.fi/pull/12

**Comment by devpanther** [comment]
@pavlovcik i think a pre-commit vercel integration will be ideal for this repo and the `pay.` subdomain..

So the URL can be explored before merged

I've attached a fix to this issue

**Comment by pavlovcik** [comment]
@0xcodercrane is working on implementing a free solution we already have working on the dollar repo. Should be up shortly to allow for rapid PR reviews.

**Comment by Wholesomebruh** [comment]
@Hodlatoor ,please provide design on how to implement submenu items in sidebar.

**Comment by Hodlatoor** [comment]
take a look on a desktop browser. It will give you an idea of what's
supposed to be on mobile. I believe currently it is set to hide when it
detects a mobile browser.

**Comment by Wholesomebruh** [comment]
Mobile browser : On uad.ubq.fi , menu is shifted to sidebar which is toggleable (hide and show) with a click . Same will be implemented here as mentioned . I just want to know , where to place the submenu as there are none on uad.ubq.fi .

**Comment by Wholesomebruh** [comment]
Mobile browser : On uad.ubq.fi , menu is shifted to sidebar which is toggleable (hide and show) with a click . Same will be implemented here as mentioned . I just want to know , where to place the submenu as there are none on uad.ubq.fi .

**Comment by Hodlatoor** [comment]
> Mobile browser : On uad.ubq.fi , menu is shifted to sidebar which is toggleable (hide and show) with a click . Same will be implemented here as mentioned . I just want to know , where to place the submenu as there are none on uad.ubq.fi .



on uad.ubq.fi the hamburger is showing on the bottom right of the screen for me and submenus do not render properly.

I would imagine placing the hamburger at the top right of all pages and sections is the way to go and making sure submenus items are easily visible and clickable. 


![Screenshot_20230815_174755_Chrome.jpg](https://github.com/ubiquity/ubq.fi/assets/121923660/d73c0bb0-09f3-47d5-8d34-988eb974a378)

**Comment by Wholesomebruh** [comment]
Thanks for confirming.

**Comment by Hodlatoor** [comment]
> Thanks for confirming.

sure. how is it looking?

**Comment by Wholesomebruh** [comment]
Css is messed up, sorry for the delay , will raise a PR by EOD.

**Comment by Hodlatoor** [comment]
Thanks for the update!

**Comment by Wholesomebruh** [comment]
@Hodlatoor , opening it back to devpool.
For bounty hunter: On opening sidebar, background and central fields doesn't reload. There is not required code in CSS file.

**Comment by pavlovcik** [comment]
> on uad.ubq.fi the hamburger is showing on the bottom right of the screen for me and submenus do not render properly.

There are no submenus. All the links work when I tested it on the dApp.
