### ISSUE TITLE
UBQ.fi top menu - correct links

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/ubq.fi#8]
site does not show the correct menu items.

menu supposed to have:
The DAO  |  The Labs |  About Us | Telegram
  -The Stable   -DevPool        - The Mission
  - The Meta    -Github link     - The Team
  -  Earn & Stake            

*note: you will find the corresponding pages in notion under "About Us".  for eg we want to use "The Team" page. not "team" in the menu.

**Comment by FibrinLab** [comment]
Hello. To clarify, you need all those as menu components?

**Comment by sergfeldman** [comment]
@Hodlatoor I am curious about what is supposed to be in the menu items 
- The Labs (as opposed to About Us) 
- The Mission

**Comment by sergfeldman** [comment]
@Hodlatoor If you are interested in my opinion in general, then at the moment it makes sense to focus the site menu on what is interesting to potential investors:
1. DevPool
2. Team 
3. GitHub 
4. Telegram

It is also necessary to have menu items for documents on Notion and our DAPP

**Comment by sergfeldman** [comment]
Per request from @Hodlatoor we defined the requirements for the menu.

**Top-level menu items:**
THE DAO 
The Labs
About Us

**The behavior**

**THE DAO** On click - go to https://dao.ubq.fi/the-dao

On hover - open the dropdown menu 
- The Stable On click - go to https://dao.ubq.fi/the-stable
- The Meta On click - go to https://dao.ubq.fi/the-meta
- Earn & Stake On click - go to https://dao.ubq.fi/earn-stake

**The Labs** On click - go to https://dao.ubq.fi/the-labs

On hover - open the dropdown menu 
- DevPool https://dao.ubq.fi/the-devpool
- Github https://github.com/ubiquity

**About Us** On click - go to https://dao.ubq.fi/about

On hover - open the dropdown menu 
- The Mission On click - go to https://dao.ubq.fi/the-mission
- The Team On click - go to https://dao.ubq.fi/the-team

**Comment by sergfeldman** [comment]
@pavlovcik Please review that these ^ requirements do not conflict with your vision for the website. 

@FibrinLab Please check that these ^ requirements are met.

**Comment by Wholesomebruh** [comment]
@sergfeldman , this is supposed to be closed , right? #5 is already merged.

**Comment by sergfeldman** [comment]
> @sergfeldman , this is supposed to be closed , right? #5 is already merged.

@Wholesomebruh Hey, thank you for the question.

@Hodlatoor Can you please decide if this issue is still actual?

**Comment by Hodlatoor** [comment]
menu is missing completely in mobile view

**Comment by Wholesomebruh** [comment]
@Hodlatoor , #6 is for that. This is for providing correct links. Please recheck. Also, #6 has a PR waiting to be merged, is there a reason for it? Sorry , for the ping. Thank You.

**Comment by Hodlatoor** [comment]
> @Hodlatoor , #6 is for that. This is for providing correct links. Please recheck. Also, #6 has a PR waiting to be merged, is there a reason for it? Sorry , for the ping. Thank You.

+ @sergfeldman 

Yes those are the correct links. I think they are originally referenced in #8 as well.  

Right now there is no top menu visible on the site

**Comment by Wholesomebruh** [comment]
Thanks for confirming, help me with the designing of menu , as in mobile , menu will be in sidebar . In uad.ubq.fi (layout was to be copied from there) , there are no submenus, so how will they be shown here?
